services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-project:/var/www/html:cached
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./laravel-project:/var/www/html:cached
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf # Монтирование пользовательской конфигурации
      - mysql-data:/var/lib/mysql              # Хранение данных MySQL
    deploy:
      resources:
        limits:
          cpus: '2'                            # Ограничение на использование процессора
          memory: 2g                           # Ограничение на использование памяти
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
